### PR TITLE
Add basic functions

### PR DESCRIPTION
**Pull request by uvchik**
Add some basic functions:

 * config.py
 *  input/output
 * basic layer
 * get polygon

### CODE REVIEW

**Comment by uvchik** [comment]
Some functions might be usefull for others as well, so please check and approve 😄

**Comment by uvchik** [comment]
@tbanze I simplified the `X_to_polygon functions` a lot. If you disagree we can roll that back. I thought that we should keep them as simple as possible because this is not the main focus of our package.

**Comment by uvchik** [comment]
I will add some more test. But basically it should be fine.

**Comment by uvchik** [comment]
Tests has been added. I think this is ready to merge. Please approve, if you agree.

**Review by sirinalibas — APPROVED** [review]
Looks good, thank you!

**Review by tbanze — APPROVED** [review]
everthing looks good, thanks

**Review by mdaneshfarfh — APPROVED** [review]
Looks good to me too. Thanks!

**Pull request merged**
